ci: Allow other steps to run if npm ci failed (but still fail the workflow if it did)

diff --git a/.github/workflows/pre-merge.yml b/.github/workflows/pre-merge.yml
--- a/.github/workflows/pre-merge.yml
+++ b/.github/workflows/pre-merge.yml
@@ -27,7 +27,15 @@ jobs:
           path: ${{ github.workspace }}/.next/cache
           key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
           restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
-      - run: npm ci --force
+      - id: npm_ci
+        run: npm ci --force
+        continue-on-error: true
+      - if: steps.npm_ci.outcome == 'failure'
+        run: npm install --force
       - run: npm run lint
       - run: npm run test
       - run: npm run build
+      - if: steps.npm_ci.outcome == 'failure'
+        run: |
+          echo "::error::npm ci failed: Run `npm install --force` to update package-lock.json"
+          exit 1
